# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-29 03:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gatekeeperapp', '0002_auto_20180329_0852'),
        ('gateuser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guard_gate', to='gatekeeperapp.Gate'),
        ),
    ]
