# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-04 05:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gatekeeperapp', '0001_initial'),
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing_rates',
            name='liner_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gatekeeperapp.Liner'),
        ),
    ]
