# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-29 03:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatekeeperapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='time_of_entry',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 3, 29, 8, 52, 2, 356985), null=True),
        ),
    ]
