# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-04 13:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gateuser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_no', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Container No.')),
                ('sz', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Sz & Te')),
                ('mty', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Mty / Ldn')),
                ('mfg_year', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Mfg Year')),
                ('gr_weight', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Gr. Weight')),
                ('tare_weight', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Tare Weight')),
                ('cbm', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Cbm')),
                ('action_required', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Action Required')),
                ('grade', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Grade')),
                ('status', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Status')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Location')),
                ('remarks', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Remarks')),
            ],
        ),
        migrations.CreateModel(
            name='Gate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gate', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Liner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liner', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Liner Name')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('gatepass', models.AutoField(primary_key=True, serialize=False)),
                ('time_of_entry', models.DateTimeField(default=datetime.datetime(2018, 3, 4, 18, 46, 48, 265421))),
                ('customer_name', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Customer Name')),
                ('cha', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'CHA/Shipper')),
                ('place_from', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Place From')),
                ('vessel_name', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Vessel Name')),
                ('vay_no', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Vay. No.')),
                ('transporter_name', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Transporter Name')),
                ('vehicle_no', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Truck No.')),
                ('bill_no', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'BL No.')),
                ('validity_date', models.DateField()),
                ('moment', models.CharField(choices=[(b'in', b'IN'), (b'out', b'OUT')], max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to='gateuser.Employee')),
                ('gate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gatekeeperapp.Gate')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gatekeeperapp.Liner')),
            ],
            options={
                'verbose_name': 'Entry',
                'verbose_name_plural': 'Entries',
            },
        ),
        migrations.AddField(
            model_name='container',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gatekeeperapp.Vehicle', verbose_name=b'Container Info'),
        ),
    ]
