# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-04 13:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatekeeperapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='time_of_entry',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 4, 19, 5, 30, 122986)),
        ),
    ]
