# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-04 05:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gateuser', '0001_initial'),
        ('gatekeeperapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to='gateuser.Employee'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='customer_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gatekeeperapp.Customer', verbose_name=b'Customer Name'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='gate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gatekeeperapp.Gate'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gatekeeperapp.Liner', verbose_name=b'Liner'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='place_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gatekeeperapp.Place', verbose_name=b'Place From'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='transporter_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gatekeeperapp.Transporter', verbose_name=b'Transporter Name'),
        ),
        migrations.AddField(
            model_name='container',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gatekeeperapp.Vehicle', verbose_name=b'Vehicle'),
        ),
    ]
