# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-04 14:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatekeeperapp', '0002_auto_20180304_1905'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='moment',
            new_name='movement_type',
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='time_of_entry',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 4, 19, 48, 46, 862018)),
        ),
    ]
