# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-06 00:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gatekeeperapp', '0003_auto_20180304_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gatekeeperapp.Vehicle', verbose_name=b'Vehicle'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='time_of_entry',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 6, 6, 0, 21, 407791)),
        ),
    ]
