# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-06 00:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gatekeeperapp', '0004_auto_20180306_0600'),
        ('gateuser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guard_gate', to='gatekeeperapp.Gate'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='designation',
            field=models.CharField(choices=[(b'guard', b'GUARD'), (b'supervisor', b'SUPERVISOR'), (b'manager', b'MANAGER')], default=1, max_length=20, verbose_name='designation'),
            preserve_default=False,
        ),
    ]
